import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDyXgkobrXgFTNZqpKgqi_XEOe-j3BOe_o" strategy="afterInteractive"></Script>
        {/* <style>
          {"@import url('https://fonts.googleapis.com/css2?family=Poiret+One&display=swap');"}
        </style> */}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
